Repository boostcampwm-2024/web02-BooBit, pull requests merged in 2024-11, with the labels that each got.

#50 프론트엔드 개발 환경 설정 #27
  FE/.gitignore
  FE/.prettierrc
  FE/README.md
  FE/eslint.config.js
  FE/index.html
  FE/package-lock.json
  FE/package.json
  FE/postcss.config.js
  FE/public/BuBu.png
  FE/public/BuBu.svg
  FE/src/App.tsx
  FE/src/index.css
  FE/src/main.tsx
  FE/src/vite-env.d.ts
  FE/tailwind.config.js
  FE/tsconfig.app.json
  FE/tsconfig.json
  FE/tsconfig.node.json
  FE/vite.config.ts
Labels: ⚙Chore, 😸FE

#54 [입출금] 자산 목록 조회
  BE/apps/balance/prisma/schema.prisma
  BE/apps/balance/src/balance.controller.spec.ts
  BE/apps/balance/src/balance.controller.ts
  BE/apps/balance/src/balance.module.ts
  BE/apps/balance/src/balance.repository.ts
  BE/apps/balance/src/balance.service.spec.ts
  BE/apps/balance/src/balance.service.ts
  BE/apps/balance/src/databases/prisma/prisma.module.ts
  BE/apps/balance/src/databases/prisma/prisma.service.ts
  BE/apps/balance/src/dto/asset.dto.ts
  BE/apps/balance/src/dto/asset.type.ts
  BE/apps/balance/src/exception/balance.exception.ts
  BE/apps/balance/src/exception/balance.exceptions.ts
  BE/apps/balance/src/exception/custom.exception.ts
  BE/apps/balance/src/exception/exception.type.ts
  BE/apps/balance/src/main.ts
  BE/package-lock.json
  BE/package.json
  FE/src/app/index.css
  FE/src/entities/MyAssetList/UI/AssetItem.tsx
  FE/src/entities/MyAssetList/UI/BoxContainer.tsx
  FE/src/entities/MyAssetList/UI/InfoBar.tsx
  FE/src/entities/MyAssetList/consts/mockImg.png
  FE/src/entities/MyAssetList/index.tsx
  FE/src/pages/MyPage/UI/MainviewLayout.tsx
  FE/src/pages/MyPage/consts/mockData.ts
  FE/src/pages/MyPage/index.tsx
  FE/src/shared/types/MyAsset.ts
  FE/tailwind.config.js
Labels: ✨Feat, 🐶BE

#66 [입출금] 자산 목록 조회
  apps/balance/prisma/schema.prisma
  apps/balance/src/balance.controller.spec.ts
  apps/balance/src/balance.controller.ts
  apps/balance/src/balance.repository.spec.ts
  apps/balance/src/balance.repository.ts
  apps/balance/src/balance.service.spec.ts
  apps/balance/src/balance.service.ts
  apps/balance/src/dto/asset.dto.ts
  apps/balance/src/dto/asset.type.ts
  apps/balance/src/dto/create.transaction.dto.ts
  libs/common/src/enums/currency-code.enum.ts
  libs/common/src/enums/index.ts
Labels: ♻️Refactor, 🐶BE

#72 [공통] 인프라 - nks와 연동하여 node에 db pod생성
  .gitignore
  apps/balance/src/balance.controller.ts
  docker-compose.yml
  kubernetes/README.md
  kubernetes/auth-db/base/kustomization.yaml
  kubernetes/auth-db/base/service.yaml
  kubernetes/auth-db/base/statefulset.yaml
  kubernetes/auth-db/base/storage.yaml
  kubernetes/balance-db/base/kustomization.yaml
  kubernetes/balance-db/base/service.yaml
  kubernetes/balance-db/base/statefulset.yaml
  kubernetes/balance-db/base/storage.yaml
  kubernetes/common/base/configmap.yaml
  kubernetes/common/base/kustomization.yaml
  kubernetes/common/base/secret.exam.yaml
  kubernetes/loadbalancer/loadbalander.dev.yaml
Labels: ⚙Chore, 🐶BE

#83 [공통] 인프라 - redis pods 생성을 위한 작업
  kubernetes/auth-db/base/kustomization.yaml
  kubernetes/auth-db/base/service.yaml
  kubernetes/auth-db/base/statefulset.yaml
  kubernetes/balance-db/base/kustomization.yaml
  kubernetes/balance-db/base/service.yaml
  kubernetes/balance-db/base/statefulset.yaml
  kubernetes/loadbalancer/loadbalander.dev.yaml
  kubernetes/redis/redis.yaml
  kubernetes/traffic/kustomization.yaml
  kubernetes/traffic/loadbalancer.yaml
  kubernetes/traffic/nginx-configmap.yaml
  kubernetes/traffic/nginx-deployment.yaml
  test/app.e2e-spec.ts
  test/jest-e2e.json
Labels: 🐶BE

#84 [로그인] API 통신
  view/src/app/main.tsx
  view/src/pages/SignIn/api/signinApi.ts
  view/src/pages/SignIn/index.tsx
  view/src/pages/SignIn/model/useSignin.ts
  view/src/pages/SignIn/model/useSigninForm.ts
  view/src/pages/SignUp/api/signupApi.ts
  view/src/pages/SignUp/index.tsx
  view/src/pages/SignUp/model/formValidationType.ts
  view/src/pages/SignUp/model/useSignup.ts
  view/src/pages/SignUp/model/useSignupForm.ts
  view/src/shared/UI/InputFeild.tsx
  view/src/shared/store/auth/authActions.ts
  view/src/shared/store/auth/authContext.tsx
  view/src/widgets/Header/UI/Logo.tsx
  view/src/widgets/Header/api/signoutApi.ts
  view/src/widgets/Header/index.tsx
  view/src/widgets/Header/model/useSignout.ts
Labels: ✨Feat, 😸FE

#85 [로그인] - 구현 인증 관련 middleware 설정
  .env.exam
  apps/auth/src/app.module.ts
  apps/auth/src/auth.controller.ts
  apps/auth/src/auth.module.ts
  apps/auth/src/auth.service.ts
  apps/auth/src/auth/auth.module.ts
  apps/auth/src/dto/login.dto.ts
  apps/auth/src/dto/signup.dto.ts
  apps/auth/src/main.ts
  apps/auth/src/passport/local.auth.guard.ts
  apps/auth/src/passport/local.strategy.ts
  apps/auth/test/auth.controller.spec.ts
  apps/auth/test/auth.service.spec.ts
  apps/auth/test/signup.dto.spec.ts
  apps/balance/src/balance.controller.ts
  apps/balance/src/balance.module.ts
  apps/balance/src/main.ts
  docker-compose.yml
  libs/common/src/index.ts
  libs/common/src/session/session-middleware.ts
  libs/prisma/src/prisma.module.ts
  libs/session/src/guard/authenticated.guard.spec.ts
  libs/session/src/guard/authenticated.guard.ts
  libs/session/src/index.ts
  libs/session/src/passport/session.serializer.spec.ts
  libs/session/src/passport/session.serializer.ts
  libs/session/src/session.middleware.ts
  libs/session/src/session.module.ts
  libs/session/tsconfig.lib.json
  nest-cli.json
  package-lock.json
  package.json
  tsconfig.json
Labels: ♻️Refactor, 🐶BE

#86 [로그인, 입출금] - CORS 처리 / 입 출금 Controller 개선, 에러 개선
  apps/auth/DockerFile
  apps/auth/src/main.ts
  apps/balance/DockerFile
  apps/balance/src/balance.controller.spec.ts
  apps/balance/src/balance.controller.ts
  apps/balance/src/balance.repository.spec.ts
  apps/balance/src/balance.service.spec.ts
  apps/balance/src/balance.service.ts
  apps/balance/src/exception/balance.exceptions.ts
  apps/balance/src/main.ts
  docker-compose.yml
  libs/common/src/cors.ts
  package-lock.json
  package.json
Labels: 🐶BE

#88 [차트] 캔들 차트, 바 차트 view 구현
  view/package-lock.json
  view/package.json
  view/src/entities/Chart/index.tsx
  view/src/entities/Chart/lib/addText.ts
  view/src/pages/Home/UI/TimeScaleItem.tsx
  view/src/pages/Home/UI/TimeScaleSelector.tsx
  view/src/pages/Home/consts/candleData.ts
  view/src/pages/Home/index.tsx
  view/src/pages/Home/lib/generateCandleData.ts
  view/src/shared/types/LayoutProps.ts
  view/src/widgets/Layout/index.tsx
  view/tsconfig.app.json
Labels: ✨Feat, 😸FE

#90 [입출금] 자산 목록 조회
  view/src/app/App.tsx
  view/src/app/main.tsx
  view/src/entities/MyAssetInfo/model/useDeposit.ts
  view/src/entities/MyAssetInfo/model/useWithdraw.ts
  view/src/pages/MyPage/api/getAssetsApi.ts
  view/src/pages/MyPage/consts/mockData.ts
  view/src/pages/MyPage/index.tsx
  view/src/pages/MyPage/model/useGetAssets.ts
Labels: ✨Feat, 😸FE

#91 [차트] 캔들 차트 시간 단위 선택 기능 구현
  view/src/entities/Chart/index.tsx
  view/src/entities/Chart/lib/createBarYAsixScale.ts
  view/src/entities/Chart/lib/createXAxisScale.ts
  view/src/entities/Chart/lib/createYAxisScale.ts
  view/src/entities/Chart/model/candleDataType.ts
  view/src/pages/Home/UI/TimeScaleItem.tsx
  view/src/pages/Home/UI/TimeScaleSelector.tsx
  view/src/pages/Home/consts/candleData.ts
  view/src/pages/Home/consts/d1candleData.ts
  view/src/pages/Home/index.tsx
  view/src/pages/Home/lib/generateCandleData.ts
  view/src/shared/types/ChartTimeScaleType.ts
Labels: ✨Feat, 😸FE

#93 [공통] toast 컴포넌트 구현
  view/.prettierrc
  view/package-lock.json
  view/package.json
  view/src/app/App.tsx
  view/src/app/main.tsx
  view/src/entities/MyAssetInfo/api/depositApi.ts
  view/src/entities/MyAssetInfo/api/withdrawApi.ts
  view/src/entities/MyAssetInfo/index.tsx
  view/src/entities/MyAssetInfo/model/useDeposit.ts
  view/src/entities/MyAssetInfo/model/useWithdraw.ts
  view/src/pages/MyPage/api/getAssetsApi.ts
  view/src/pages/SignIn/api/signinApi.ts
  view/src/pages/SignIn/model/useSignin.ts
  view/src/pages/SignUp/api/signupApi.ts
  view/src/pages/SignUp/model/useSignup.ts
  view/src/shared/UI/Toast.tsx
  view/src/shared/consts/baseUrl.ts
  view/src/shared/consts/errorMessages.ts
  view/src/shared/consts/successMessage.ts
  view/src/shared/images/error.svg
  view/src/shared/images/info.svg
  view/src/shared/images/success.svg
  view/src/shared/store/ToastContext.tsx
  view/src/widgets/Header/api/signoutApi.ts
  view/src/widgets/Header/model/useSignout.ts
Labels: ✨Feat, 😸FE

#118 [차트] 호가창 view 구현
  view/src/entities/OrderBook/UI/OrderItem.tsx
  view/src/entities/OrderBook/index.tsx
  view/src/entities/OrderBook/model/OrderType.ts
  view/src/pages/Home/UI/Title.tsx
  view/src/pages/Home/consts/currentPriceMockData.ts
  view/src/pages/Home/consts/orderBookMockData.ts
  view/src/pages/Home/index.tsx
  view/src/shared/images/down.svg
  view/src/shared/images/up.svg
  view/tailwind.config.js
Labels: ✨Feat, 😸FE

#119 [차트] 매수 매도 주문 view 구현
  view/.prettierrc
  view/src/app/App.tsx
  view/src/entities/Chart/index.tsx
  view/src/entities/MyAssetInfo/UI/TabItem.tsx
  view/src/entities/MyAssetInfo/index.tsx
  view/src/entities/MyAssetList/index.tsx
  view/src/entities/OrderBook/UI/OrderItem.tsx
  view/src/entities/OrderBook/index.tsx
  view/src/entities/OrderPanel/UI/Button.tsx
  view/src/entities/OrderPanel/UI/InputNumber.tsx
  view/src/entities/OrderPanel/UI/SectionBlock.tsx
  view/src/entities/OrderPanel/api/postBuyApi.ts
  view/src/entities/OrderPanel/const/orderCategory.ts
  view/src/entities/OrderPanel/index.tsx
  view/src/entities/OrderPanel/model/RequestDataType.ts
  view/src/entities/OrderPanel/model/useGetAssets.ts
  view/src/entities/OrderPanel/model/useOrderAmount.ts
  view/src/entities/OrderPanel/model/usePostBuy.ts
  view/src/pages/Home/UI/TimeScaleSelector.tsx
  view/src/pages/Home/index.tsx
  view/src/pages/MyPage/UI/CategoryItem.tsx
  view/src/pages/SignUp/model/useSignup.ts
  view/src/shared/UI/Tab.tsx
  view/src/shared/UI/TabItem.tsx
  view/src/shared/consts/errorMessages.ts
  view/src/shared/consts/successMessage.ts
  view/src/shared/model/useWebSocket.ts
  view/src/shared/types/ChartTimeScaleType.ts
  view/src/shared/types/socket/BuyAndSellType.ts
  view/src/shared/types/socket/CandleChartType.ts
  view/src/shared/types/socket/CurrentPriceType.ts
  view/src/shared/types/socket/SocketEventType.ts
  view/src/shared/types/socket/TradeType.ts
  view/src/shared/types/socket/WebSocketMessageType.ts
  view/src/widgets/Header/index.tsx
  view/src/widgets/Header/model/useSignout.ts
  view/src/widgets/Layout/index.tsx
Labels: ✨Feat, 😸FE

#122 [차트] - 체결 목록 view 구현
  view/src/entities/OrderBook/UI/OrderItem.tsx
  view/src/entities/TradeRecords/UI/TradeRecordRow.tsx
  view/src/entities/TradeRecords/UI/TradeRecordsCell.tsx
  view/src/entities/TradeRecords/index.tsx
  view/src/pages/Home/consts/tradeHistoryMockData.ts
  view/src/pages/Home/index.tsx
Labels: ✨Feat, 😸FE

#124 🐛Fix: x scale 변수 명 변경
  view/src/entities/Chart/index.tsx
  view/src/entities/Chart/lib/createXAxisScale.ts
Labels: 🐛Fix, 😸FE

#128 [마이페이지] 유저 정보 view 구현
  view/src/entities/MyAssetList/index.tsx
  view/src/entities/MyInfo/UI/InfoItem.tsx
  view/src/entities/MyInfo/const/myInfoMockData.ts
  view/src/entities/MyInfo/index.tsx
  view/src/pages/MyPage/index.tsx
  view/tailwind.config.js
Labels: ✨Feat, 😸FE

#136 [마이페이지] 내 정보 API 통신 연결
  view/src/entities/MyInfo/api/getProfileApi.ts
  view/src/entities/MyInfo/const/myInfoMockData.ts
  view/src/entities/MyInfo/index.tsx
  view/src/entities/MyInfo/model/useGetProfile.ts
  view/src/entities/OrderPanel/model/useGetAssets.ts
  view/src/pages/MyPage/consts/mockData.ts
  view/src/pages/MyPage/index.tsx
  view/src/widgets/CashTransaction/api/getAssetsApi.ts
  view/src/widgets/CashTransaction/index.tsx
  view/src/widgets/CashTransaction/model/useGetAssets.ts
Labels: ✨Feat, 😸FE

#141 [마이페이지] 매도, 미체결 내역 API 연결
  view/src/entities/MyOpenOrders/api/getPendingApi.ts
  view/src/entities/MyOpenOrders/const/mockData.ts
  view/src/entities/MyOpenOrders/index.tsx
  view/src/entities/MyOpenOrders/model/OrderType.ts
  view/src/entities/MyOpenOrders/model/useGetPending.ts
  view/src/entities/MyTradeHistory/index.tsx
  view/src/entities/OrderPanel/api/postSellApi.ts
  view/src/entities/OrderPanel/index.tsx
  view/src/entities/OrderPanel/model/usePostSell.ts
  view/src/shared/consts/errorMessages.ts
  view/src/shared/consts/successMessage.ts
Labels: ✨Feat, 😸FE

#143 [입출금] 입출금 내역 조회 API 연결
  view/src/app/App.tsx
  view/src/entities/MyAssetInfo/UI/TransactionLogItem.tsx
  view/src/entities/MyAssetInfo/UI/TransactionLogs.tsx
  view/src/entities/MyAssetInfo/api/depositApi.ts
  view/src/entities/MyAssetInfo/api/getTransactionsApi.ts
  view/src/entities/MyAssetInfo/api/withdrawApi.ts
  view/src/entities/MyAssetInfo/consts/historyMockData.ts
  view/src/entities/MyAssetInfo/index.tsx
  view/src/entities/MyAssetInfo/model/AssetType.ts
  view/src/entities/MyAssetInfo/model/TransactionType.ts
  view/src/entities/MyAssetInfo/model/TransactionsRequestType.ts
  view/src/entities/MyAssetInfo/model/useGetTransactions.ts
Labels: ✨Feat, 😸FE

#151 [마켓] 이전 체결, 차트 데이터 웹 소켓 연결
  view/src/entities/Chart/index.tsx
  view/src/entities/TradeRecords/index.tsx
  view/src/pages/Home/consts/d1candleData.ts
  view/src/pages/Home/consts/tradeHistoryMockData.ts
  view/src/pages/Home/index.tsx
  view/src/shared/model/useWebSocket.ts
  view/src/shared/types/RecordType.ts
  view/src/shared/types/socket/TradeType.ts
Labels: ✨Feat, 😸FE

#154 [마이페이지] 거래내역, 주문 쥐소 mock API 연결
  view/package-lock.json
  view/package.json
  view/public/mockServiceWorker.js
  view/src/__mocks/browser.ts
  view/src/__mocks/handlers/balanceHandlers.ts
  view/src/__mocks/handlers/index.ts
  view/src/__mocks/handlers/transactionHandlers.ts
  view/src/app/App.tsx
  view/src/app/main.tsx
  view/src/entities/MyOpenOrders/api/deleteOrderApi.ts
  view/src/entities/MyOpenOrders/index.tsx
  view/src/entities/MyOpenOrders/model/useDeleteOrder.ts
  view/src/entities/MyTradeHistory/api/getOrdersApi.ts
  view/src/entities/MyTradeHistory/const/mockData.ts
  view/src/entities/MyTradeHistory/const/status.ts
  view/src/entities/MyTradeHistory/index.tsx
  view/src/entities/MyTradeHistory/model/OrderType.ts
  view/src/entities/MyTradeHistory/model/useGetOrders.ts
  view/src/entities/OrderBook/index.tsx
  view/src/pages/Home/UI/Title.tsx
  view/src/pages/Home/consts/currentPriceMockData.ts
  view/src/pages/Home/index.tsx
  view/src/shared/consts/errorMessages.ts
  view/src/shared/consts/successMessage.ts
  view/src/shared/types/socket/CandleChartType.ts
  view/src/shared/types/socket/CandleSocketType.ts
  view/src/shared/types/socket/CurrentPriceType.ts
  view/src/shared/types/socket/SocketEventType.ts
  view/src/shared/types/socket/WebSocketMessageType.ts
  view/tsconfig.app.json
Labels: ✨Feat, 😸FE

#155 [주문] 주문 취소 및 미체결 조회 구현
  microservice/apps/balance/src/balance.controller.ts
  microservice/apps/balance/src/balance.repository.ts
  microservice/apps/balance/src/balance.service.ts
  microservice/apps/trade/prisma/schema.prisma
  microservice/apps/trade/src/dto/trade.buy.order.type.ts
  microservice/apps/trade/src/dto/trade.sell.order.type.ts
  microservice/apps/trade/src/trade.balance.service.ts
  microservice/apps/trade/src/trade.controller.spec.ts
  microservice/apps/trade/src/trade.processor.ts
  microservice/apps/trade/src/trade.repository.ts
  microservice/apps/trade/src/trade.service.spec.ts
  microservice/apps/trade/src/trade.service.ts
  microservice/apps/transaction/prisma/schema.prisma
  microservice/apps/transaction/src/dto/order.pending.response.dto.ts
  microservice/apps/transaction/src/dto/pending.buy.order.type.ts
  microservice/apps/transaction/src/dto/pending.sell.order.type.ts
  microservice/apps/transaction/src/transaction.controller.ts
  microservice/apps/transaction/src/transaction.queue.service.ts
  microservice/apps/transaction/src/transaction.repository.ts
  microservice/apps/transaction/src/transaction.service.ts
  microservice/libs/common/src/enums/order-status.enum.ts
  microservice/libs/common/src/enums/order-type.enum.ts
  microservice/libs/grpc/proto/trade.proto
  microservice/libs/grpc/src/dto/trade.cancel.request.dto.ts
  microservice/libs/grpc/src/dto/trade.history.request.dto.ts
  microservice/libs/grpc/src/dto/trade.request.dto.ts
  microservice/libs/grpc/src/trade.interface.ts
Labels: ♻️Refactor, ✨Feat, 🐶BE

#159 [주문] 주문 내역 조회
  microservice/apps/balance/src/balance.repository.ts
Labels: 🐛Fix, 🐶BE

#160 [마켓] 체결 내역, 호가창 mockiing 웹 소켓 연결
  view/src/__mocks/browser.ts
  view/src/__mocks/handlers/index.ts
  view/src/__mocks/handlers/websocketHandlers.ts
  view/src/entities/OrderBook/UI/OrderItem.tsx
  view/src/entities/OrderBook/index.tsx
  view/src/pages/Home/consts/orderBookMockData.ts
  view/src/pages/Home/index.tsx
  view/src/shared/types/socket/BuyAndSellType.ts
  view/src/shared/types/socket/OrderType.ts
Labels: ✨Feat, 😸FE

#164 [마켓] 캔들 차트 msw mocking 연결
  view/src/__mocks/handlers/balanceHandlers.ts
  view/src/__mocks/handlers/index.ts
  view/src/__mocks/handlers/transactionHandlers.ts
  view/src/__mocks/handlers/websocketHandlers.ts
  view/src/entities/MyOpenOrders/model/useDeleteOrder.ts
  view/src/pages/Home/index.tsx
  view/src/pages/Home/lib/generateCandleData.ts
Labels: ✨Feat, 😸FE

#186 [조회] 소수점 고정
  microservice/apps/balance/src/balance.service.ts
  microservice/apps/balance/src/dto/asset.dto.ts
  microservice/apps/transaction/src/dto/order.pending.response.dto.ts
  microservice/apps/transaction/src/dto/trade.get.response.dto.ts
Labels: 🐛Fix, 🐶BE

#187 [fix] 에러 수정
  view/.env.exam
  view/.env.production
  view/src/entities/Chart/index.tsx
  view/src/entities/MyAssetInfo/api/depositApi.ts
  view/src/entities/MyAssetInfo/api/getTransactionsApi.ts
  view/src/entities/MyAssetInfo/api/withdrawApi.ts
  view/src/entities/MyInfo/api/getProfileApi.ts
  view/src/entities/MyOpenOrders/api/deleteOrderApi.ts
  view/src/entities/MyOpenOrders/api/getPendingApi.ts
  view/src/entities/MyOpenOrders/model/useDeleteOrder.ts
  view/src/entities/MyTradeHistory/api/getOrdersApi.ts
  view/src/entities/MyTradeHistory/index.tsx
  view/src/entities/OrderBook/index.tsx
  view/src/entities/OrderPanel/api/postBuyApi.ts
  view/src/entities/OrderPanel/api/postSellApi.ts
  view/src/entities/OrderPanel/index.tsx
  view/src/pages/Home/index.tsx
  view/src/pages/SignIn/api/signinApi.ts
  view/src/pages/SignUp/api/signupApi.ts
  view/src/shared/api/getAssetsApi.ts
  view/src/widgets/Header/api/signoutApi.ts
Labels: 🐛Fix

#188 [Fix] 에러 수정
  view/.env.exam
  view/src/entities/Chart/index.tsx
  view/src/entities/MyAssetInfo/UI/TransactionForm.tsx
  view/src/entities/OrderPanel/index.tsx
Labels: 🐛Fix

#190 🐛Fix. candle chart init 에러 해결
  view/src/pages/Home/index.tsx
  view/src/shared/model/useWebSocket.ts
Labels: 🐛Fix

#191 [마켓] 호가창 주문 가능 금액/수량 API 교체
  view/src/app/App.tsx
  view/src/entities/OrderPanel/api/getAvailableAssetApi.ts
  view/src/entities/OrderPanel/index.tsx
  view/src/entities/OrderPanel/model/useGetAvailableAsset.ts
  view/src/entities/OrderPanel/model/usePostBuy.ts
  view/src/entities/OrderPanel/model/usePostSell.ts
  view/src/pages/Home/index.tsx
Labels: ✨Feat, 😸FE

#192 [Fix] 웹소켓 open 전 이벤트 전송 에러
  view/src/entities/Chart/index.tsx
  view/src/entities/Chart/lib/createXAxisScale.ts
  view/src/entities/Chart/lib/updateMarketText.ts
  view/src/entities/Chart/model/candleDataType.ts
  view/src/pages/Home/index.tsx
Labels: 🐛Fix, 😸FE

#197 [공통] 데이터 형식 변경
  view/src/entities/MyAssetInfo/UI/TransactionForm.tsx
  view/src/entities/MyAssetInfo/UI/TransactionLogItem.tsx
  view/src/entities/MyAssetInfo/index.tsx
  view/src/entities/MyAssetList/UI/AssetItem.tsx
  view/src/entities/MyOpenOrders/index.tsx
  view/src/entities/MyOrderHistory/index.tsx
  view/src/entities/MyTradeHistory/index.tsx
  view/src/entities/OrderPanel/UI/InputNumber.tsx
  view/src/entities/OrderPanel/index.tsx
  view/src/entities/OrderPanel/model/useOrderAmount.ts
  view/src/entities/TradeRecords/index.tsx
  view/src/shared/model/formatDate.ts
  view/src/shared/model/formatPrice.ts
Labels: 😸FE

#198 [마켓] 메인 페이지 컴포넌트 개선
  view/src/app/App.tsx
  view/src/entities/Chart/index.tsx
  view/src/entities/Chart/lib/updateMarketText.ts
  view/src/entities/TradeRecords/index.tsx
  view/src/pages/Home/UI/Title.tsx
  view/src/pages/Home/index.tsx
  view/src/shared/model/calculateChangeRate.ts
Labels: 😸FE

#199 [체결] 매수 매도 접수 후 buy_order, sell_order에 만들어지는 순서를 큐에서 진행하도록 변경
  microservice/apps/balance/src/balance.repository.ts
  microservice/apps/trade/src/trade.processor.ts
  microservice/apps/trade/src/trade.repository.ts
  microservice/apps/trade/src/trade.service.ts
  microservice/apps/transaction/src/transaction.controller.ts
  microservice/apps/transaction/src/transaction.queue.service.ts
  microservice/apps/transaction/src/transaction.repository.ts
  microservice/apps/transaction/src/transaction.service.ts
  microservice/libs/grpc/proto/trade.proto
  microservice/libs/grpc/src/dto/trade.buyer.request.dto.ts
  microservice/libs/grpc/src/dto/trade.order.dto.ts
  microservice/libs/grpc/src/dto/trade.seller.request.dto.ts
Labels: 🐛Fix, 🐶BE

#200 [Fix] 체결, 입출금 에러 수정
  view/src/__mocks/handlers/websocketHandlers.ts
  view/src/entities/MyAssetInfo/index.tsx
  view/src/entities/TradeRecords/index.tsx
  view/src/pages/Home/index.tsx
  view/src/shared/consts/errorMessages.ts
  view/src/shared/types/RecordType.ts
  view/src/shared/types/socket/TradeType.ts
Labels: 😸FE

#201 [마이페이지] 미체결 내역 조회 API 변경
  view/src/entities/MyOpenOrders/api/getPendingApi.ts
  view/src/entities/MyOpenOrders/index.tsx
  view/src/entities/MyOpenOrders/model/useGetPending.ts
Labels: 🐛Fix, 😸FE

#203 [Fix] UX 개선 및 에러 해결
  view/src/app/App.tsx
  view/src/entities/Chart/index.tsx
  view/src/entities/MyAssetInfo/UI/TransactionForm.tsx
  view/src/entities/MyAssetList/UI/AssetItem.tsx
  view/src/entities/OrderPanel/UI/InputNumber.tsx
  view/src/entities/TradeRecords/index.tsx
  view/src/pages/Home/index.tsx
  view/src/pages/SignUp/UI/Guideline.tsx
  view/src/pages/SignUp/model/useSignupForm.ts
  view/src/shared/UI/SubmitButton.tsx
  view/src/shared/UI/TabItem.tsx
  view/src/widgets/Header/index.tsx
  view/src/widgets/Header/model/useSignout.ts
Labels: 🐛Fix, 😸FE
